[project]
name = "genrenator-uv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.27.2",
    "mistune>=3.0.2",
    "quart>=0.19.6",
]
